server:
  port: 5701

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 365373011
    url: jdbc:mysql://192.168.18.191:3306/qq_bot
  redis:
    host: 192.168.
    port: 6379
    password: 365373011
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.lyra.qqbot.processor: debug